### ISSUE TITLE
DeprecationWarning: Invalid `main` field

### ISSUE THREAD

**Issue by chandlervdw** [christopherafbjur/sanity-plugin-icon-picker#25]
When running `sanity graphql deploy`:

```
DeprecationWarning: Invalid 'main' field in '../node_modules/sanity-plugin-icon-picker/node_modules/react-icons/package.json' of 'lib'. Please either fix that or report it to the module author
```

**Comment by codingChewie** [comment]
Any status on this and if [React Icons](https://github.com/react-icons/react-icons/releases/tag/v4.5.1) will be upgraded from version:

```
4.2.0
```

to:

```
4.5.1
```

as this error would appear to be causing a Netlify build failure as the terminal error prompts to proceed from Sanity and because that isnt an option it then results in an error of:

 > Build failed - Command failed with exit code 134

On research of the `exit code 134` there is a linked [forum article](https://answers.netlify.com/t/build-failed-command-failed-with-exit-code-134/53757) mentioning this error could be causing a memory leak. Upgrading versions will also resolve the [PR for adding Simple Icons](https://github.com/christopherafbjur/sanity-plugin-icon-picker/pull/23).

**Comment by christopherafbjur** [comment]
Thank you for reporting this and sorry for the delay. I will start looking into fixing these recent issues asap!

**Comment by christopherafbjur** [comment]
> > Thank you for reporting this and sorry for the delay. I will start looking into fixing these recent issues asap!
> 
> 
> 
> Just curious if you would be upgrading to Sanity v3?

Yes that's something I will do as well. Just haven't decided if I will do that in the same release. Might be better to fix this first for backward compatibility and create a new release for v3
